language: node_js

node_js:
  - 7
  - 6
  - 5

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm run lint
  - npm run test
  - npm run build
  

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  slack: polidevelopers:b2ilF8FkLWBCps2rGq0gOqjr

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
